name: Push to DockerHub

on:
  workflow_run:
    workflows: ["Unit Tests"]
    branches:
      - main
    types:
      - completed

jobs:
  main:
    name: Build and upload Docker image
    strategy:
      matrix:
        python:
          - "3.7"
        os:
          - ubuntu-latest
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

      TRAVIS_REPO_SLUG: ${{ github.repository }}
      TRAVIS_BRANCH: ${{ github.head_ref }}
      TRAVIS_PULL_REQUEST: ${{ github.event.number }}

      DOCKER_DEST: "riccardomurri/elasticluster"
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    runs-on: ubuntu-18.04
    steps:

    #
    # Install from sources
    #
    - name: Checkout ElastiCluster sources
      # see: https://github.com/actions/checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install `pip` and `setuptools`
      run: "pip install --upgrade 'setuptools' 'pip>=8.1.2'"

    - name: Install ElastiCluster from sources
      run: "pip install ."

    #
    # Upload Docker image
    #
    - name: Publish to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: "riccardomurri/elasticluster"
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        # FIXME: should be `latest,master` on the master branch, but `pr#XXX` on other branches
        #tags: "latest,${TRAVIS_BRANCH}"
        # push tags/release by their git name (e.g. refs/tags/MY_TAG_NAME)
        tag_names: true
        # push tags using the semver syntax by their git name
        # (e.g. refs/tags/v1.2.3 will push four docker tags: 1.2.3, 1.2 and 1)
        tag_semver: true
