name: Unit Tests

on:
  push:
  pull_request:
    branches:
    - master

jobs:
  main:
    name: Run Unit Tests
    strategy:
      matrix:
        python:
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
        os:
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
          - macos-11.0
          # apparently Python is not available on `macosx-10.5`
          #- macos-10.5
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

    runs-on: ${{ matrix.os }}
    steps:

    #
    # Install from sources
    #
    - name: Checkout ElastiCluster sources
      # see: https://github.com/actions/checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install `pip` and `setuptools`
      run: "pip install --upgrade 'setuptools' 'pip>=8.1.2'"

    - name: Install ElastiCluster from sources
      run: "pip install ."

    #
    # Unit tests
    #
    - name: Install test dependencies
      run: "pip install 'pytest' 'pytest-cov' 'mock' 'tox' 'codecov'"

    - name: Run unit tests
      run: "pytest -v --cov=elasticluster --cov-branch"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        env_vars: OS,PYTHON
